### ISSUE TITLE
CCL package local nicknames

### ISSUE THREAD

**Issue by phoe** [t-cool/ej#1]
Hey,

making an issue here because I didn't get a response to a mail, and I didn't see any other means of contacting you on GitHub.

I've patched CCL to have package-local nicknames. https://www.bountysource.com/issues/55429455-implement-package-local-nicknames-in-ccl I think I've done it, it got merged.

Are you willing to accept my solution for bounty purposes?

Cheers!
~phoe

**Comment by t-cool** [comment]
Hi, phoe.
Sorry for the delay!
I accepted the bounty.  
Please have a check :)

**Comment by phoe** [comment]
Thank you!
